export enum ACTION_TYPES {
  GET_PLAYLIST,
  GET_PLAYLIST_ID,
  CREATE_PLAYLIST,
  UPDATE_PLAYLIST,
  DELETE_PLAYLIST,
  GET_SONGS,
  CREATE_SONGS,
  CREATE_SONGS_PLAYLIST,
  UPDATE_SONGS,
  DELETE_SONGS,
}
